// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Guia")]
    public partial class GuiaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Guia", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Guia.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
await testRunner.AndAsync("accede al módulo \'Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
await testRunner.AndAsync("accede al submódulo \'Nueva Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
await testRunner.AndAsync("el usuario agrega el concepto \'400000437\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
await testRunner.AndAsync("selecciona al cliente con documento \'60587924\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
await testRunner.AndAsync("selecciona el tipo de entrega", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Guia de para transporte publico <condicion>")]
        [NUnit.Framework.CategoryAttribute("Publico")]
        [NUnit.Framework.TestCaseAttribute("100", "60587924", "28/11/2025", "100", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("101", "60587924", "", "100", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("102", "60587924", "28/11/2025", "0", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("103", "60587924", "28/11/2025", "100", "0", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("104", "60587924", "28/11/2025", "100", "20", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("105", "60587924", "28/11/2025", "100", "20", "20608671880", "", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("106", "60587924", "28/11/2025", "100", "20", "20608671880", "Av. Siempre Viva 123", "", null)]
        [NUnit.Framework.TestCaseAttribute("107", "60587924", "", "0", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("108", "60587924", "", "100", "0", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("109", "60587924", "", "100", "20", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("110", "60587924", "28/11/2025", "0", "0", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("111", "60587924", "28/11/2025", "0", "20", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("112", "60587924", "28/11/2025", "100", "0", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("113", "60587924", "28/11/2025", "100", "20", "20608671880", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("114", "60587924", "", "0", "0", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("115", "60587924", "", "0", "20", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("116", "60587924", "", "100", "0", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("117", "60587924", "28/11/2025", "0", "0", "00000000000", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("118", "60587924", "28/11/2025", "0", "0", "20608671880", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("119", "60587924", "", "100", "20", "00000000000", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("120", "60587924", "", "0", "0", "00000000000", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("121", "60587924", "28/11/2025", "abc", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("122", "60587924", "28/11/2025", "100", "xyz", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("123", "60587924", "32/13/2025", "100", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("124", "60587924", "28/11/2025", "-5", "20", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("125", "60587924", "28/11/2025", "100", "-1", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("126", "60587924", "28/11/2025", "0", "0", "12345678901", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("127", "60587924", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("128", "60587924", "28/11/2025", "50", "1", "20608671880", "Jr. Sven Ericson N° 109", "Av. SpringField 742", null)]
        [NUnit.Framework.TestCaseAttribute("129", "60587924", "28/11/2025", "1", "1", "20608671880", "Calle A 123", "Calle B 456", null)]
        [NUnit.Framework.TestCaseAttribute("130", "60587924", "20/11/2025", "10.5", "2", "20608671880", "JR. LOS JASMÍNES", "JR. VENABIDES", null)]
        [NUnit.Framework.TestCaseAttribute("131", "60587924", "01/12/2025", "999.99", "100", "20608671880", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        public async System.Threading.Tasks.Task GuiaDeParaTransportePublicoCondicion(string condicion, string destinatario, string fecha, string p_Bruto, string n_Bultos, string n_Identificacion, string detalle_Origen, string detalle_Destino, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Publico"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("destinatario", destinatario);
            argumentsOfScenario.Add("fecha", fecha);
            argumentsOfScenario.Add("p_bruto", p_Bruto);
            argumentsOfScenario.Add("n_bultos", n_Bultos);
            argumentsOfScenario.Add("n_identificacion", n_Identificacion);
            argumentsOfScenario.Add("detalle_origen", detalle_Origen);
            argumentsOfScenario.Add("detalle_destino", detalle_Destino);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Guia de para transporte publico <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 14
 await testRunner.WhenAsync(string.Format("selecciona destinatario \'{0}\'", destinatario), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
 await testRunner.AndAsync(string.Format("fecha inicio translado \'{0}\'", fecha), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync(string.Format("introduce el peso bruto \'{0}\'", p_Bruto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("introduce el numero de bultos \'{0}\'", n_Bultos), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("selecciona la modalidad de transporte \'TRANSPORTE PÚBLICO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("introduce el numero de identifacion \'{0}\'", n_Identificacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync(string.Format("introduce el detalle de origen \'{0}\'", detalle_Origen), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync(string.Format("selecciona el detalle de destino \'{0}\'", detalle_Destino), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync("guardar guia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Guia para transporte privado <condicion>")]
        [NUnit.Framework.CategoryAttribute("Privado")]
        [NUnit.Framework.TestCaseAttribute("200", "60587924", "28/11/2025", "200", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("201", "60587924", "", "200", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("202", "60587924", "28/11/2025", "0", "30", "60587924", "12345678", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("203", "60587924", "28/11/2025", "200", "0", "60587924", "12345678", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("204", "60587924", "28/11/2025", "200", "30", "00000000", "12345678", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("205", "60587924", "28/11/2025", "200", "30", "1234567", "12345678", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("206", "60587924", "28/11/2025", "200", "30", "60587924", "", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("207", "60587924", "28/11/2025", "200", "30", "60587924", "123456789", "", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("208", "60587924", "28/11/2025", "200", "30", "60587924", "123456789", "XYZ987", "", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("209", "60587924", "28/11/2025", "200", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "", null)]
        [NUnit.Framework.TestCaseAttribute("210", "60587924", "", "0", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("211", "60587924", "", "200", "0", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("212", "60587924", "28/11/2025", "0", "0", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("213", "60587924", "28/11/2025", "200", "30", "00000000", "", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("214", "60587924", "28/11/2025", "200", "30", "60587924", "", "", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("215", "60587924", "28/11/2025", "200", "30", "00000000", "12345678", "XYZ987", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("216", "60587924", "", "0", "0", "00000000", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("217", "60587924", "32/13/2025", "200", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("218", "60587924", "28/11/2025", "abc", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("219", "60587924", "28/11/2025", "200", "xyz", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("220", "60587924", "28/11/2025", "-1", "30", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("221", "60587924", "28/11/2025", "200", "-5", "60587924", "123456789", "XYZ987", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("222", "60587924", "20/11/2025", "1", "1", "60587924", "A1-999999", "ABC123", "JR. LOS JASMÍNES", "JR. VENABIDES", null)]
        [NUnit.Framework.TestCaseAttribute("223", "60587924", "01/12/2025", "999.99", "100", "60587924", "B2-111111", "DEF456", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("224", "60587924", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("225", "60587924", "28/11/2025", "0", "0", "00000000", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("226", "60587924", "28/11/2025", "0", "0", "60587924", "", "XYZ987", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("227", "60587924", "28/11/2025", "0", "0", "60587924", "12345678", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("228", "60587924", "28/11/2025", "0", "0", "60587924", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("229", "60587924", "28/11/2025", "10.5", "2", "60587924", "99999999", "JKL789", "Calle A 123", "Calle B 456", null)]
        [NUnit.Framework.TestCaseAttribute("230", "60587924", "28/11/2025", "5", "1", "60587924", "L-1234567", "MNO321", "Av. Siempre Viva 123", "Calle Falsa 456", null)]
        [NUnit.Framework.TestCaseAttribute("231", "60587924", "28/11/2025", "50", "10", "45879632", "55667788", "PQR654", "Av. Peru 123", "Av. Lima 456", null)]
        public async System.Threading.Tasks.Task GuiaParaTransportePrivadoCondicion(string condicion, string destinatario, string fecha, string p_Bruto, string n_Bultos, string n_Identificacion, string n_Licencia, string placa, string detalle_Origen, string detalle_Destino, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Privado"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("destinatario", destinatario);
            argumentsOfScenario.Add("fecha", fecha);
            argumentsOfScenario.Add("p_bruto", p_Bruto);
            argumentsOfScenario.Add("n_bultos", n_Bultos);
            argumentsOfScenario.Add("n_identificacion", n_Identificacion);
            argumentsOfScenario.Add("n_licencia", n_Licencia);
            argumentsOfScenario.Add("placa", placa);
            argumentsOfScenario.Add("detalle_origen", detalle_Origen);
            argumentsOfScenario.Add("detalle_destino", detalle_Destino);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Guia para transporte privado <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 60
 await testRunner.WhenAsync(string.Format("selecciona destinatario \'{0}\'", destinatario), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.AndAsync(string.Format("fecha inicio translado \'{0}\'", fecha), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync(string.Format("introduce el peso bruto \'{0}\'", p_Bruto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
 await testRunner.AndAsync(string.Format("introduce el numero de bultos \'{0}\'", n_Bultos), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("selecciona la modalidad de transporte \'TRANSPORTE PRIVADO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync(string.Format("introduce el numero de identifacion \'{0}\'", n_Identificacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync(string.Format("introduce el numero de licencia\'{0}\'", n_Licencia), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.AndAsync(string.Format("introduce la placa \'{0}\'", placa), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.AndAsync(string.Format("introduce el detalle de origen \'{0}\'", detalle_Origen), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.AndAsync(string.Format("selecciona el detalle de destino \'{0}\'", detalle_Destino), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.ThenAsync("guardar guia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
