// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NuevaVenta")]
    public partial class NuevaVentaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NuevaVenta", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevaVenta.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
await testRunner.AndAsync("accede al módulo \'Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
await testRunner.AndAsync("accede al submódulo \'Nueva Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de una nueva venta con pago al contado <condicion>")]
        [NUnit.Framework.CategoryAttribute("RegistrarVenta")]
        [NUnit.Framework.TestCaseAttribute("1", "400000437", "1", "60587924", "FACTURA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("2", "400000437", "1", "60587924", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("3", "400000437", "1", "60587924", "BOLETA DE VENTA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("4", "400000437", "1", "60587924", "BOLETA DE VENTA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("5", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("6", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("7", "400000437", "1", "20608671880", "BOLETA DE VENTA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("8", "400000437", "1", "20608671880", "BOLETA DE VENTA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("9", "400000437", "9999", "60587924", "FACTURA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("10", "400000437", "9999", "60587924", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("11", "400000437", "9999", "60587924", "BOLETA DE VENTA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("12", "400000437", "9999", "60587924", "BOLETA DE VENTA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("13", "400000437", "9999", "20608671880", "BOLETA DE VENTA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("14", "400000437", "9999", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("15", "400000437", "9999", "20608671880", "FACTURA ELECTRONICA", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("16", "400000437", "9999", "20608671880", "BOLETA DE VENTA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("17", "", "1", "60587924", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("18", "", "1", "60587924", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("19", "", "1", "60587924", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("20", "", "1", "60587924", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("21", "", "1", "20608671880", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("22", "", "1", "20608671880", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("23", "", "1", "20608671880", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("24", "", "1", "20608671880", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("25", "", "9999", "60587924", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("26", "", "9999", "60587924", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("27", "", "9999", "20608671880", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("28", "", "9999", "20608671880", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("29", "", "9999", "20608671880", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("30", "", "9999", "20608671880", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("31", "", "9999", "60587924", "NOTA DE VENTA (INTERNA)", "INMEDIATA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("32", "", "9999", "60587924", "NOTA DE VENTA (INTERNA)", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("33", "400000437", "-4", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("34", "400000437", "0", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("35", "400000437", "20", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("36", "400000437", "9999", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "130.00", null)]
        [NUnit.Framework.TestCaseAttribute("37", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "-5", null)]
        [NUnit.Framework.TestCaseAttribute("38", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "0", null)]
        [NUnit.Framework.TestCaseAttribute("39", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "1", null)]
        [NUnit.Framework.TestCaseAttribute("40", "400000437", "1", "20608671880", "FACTURA ELECTRONICA", "DIFERIDA", "CO", "EF", "10", null)]
        public async System.Threading.Tasks.Task RegistroDeUnaNuevaVentaConPagoAlContadoCondicion(string condicion, string concepto, string cantidad, string documento, string tipo_Comprobante, string tipo_Entrega, string tipo_Pago, string medio_Pago, string informacion_Pago, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarVenta"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("concepto", concepto);
            argumentsOfScenario.Add("cantidad", cantidad);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("tipo_comprobante", tipo_Comprobante);
            argumentsOfScenario.Add("tipo_entrega", tipo_Entrega);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("medio_pago", medio_Pago);
            argumentsOfScenario.Add("informacion_pago", informacion_Pago);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de una nueva venta con pago al contado <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 12
 await testRunner.WhenAsync(string.Format("el usuario agrega el concepto \'{0}\'", concepto), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
 await testRunner.AndAsync(string.Format("ingresa la cantidad \'{0}\'", cantidad), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("selecciona igv", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("selecciona al cliente con documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("selecciona el tipo de comprobante \'{0}\'", tipo_Comprobante), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("selecciona el tipo de entrega \'{0}\'", tipo_Entrega), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("selecciona el medio de pago \'{0}\'", medio_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync(string.Format("ingrese la informacion del pago \'{0}\'", informacion_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
