// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Pago")]
    public partial class PagoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Pago", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Pago.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 4
await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
await testRunner.AndAsync("accede al módulo \'Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
await testRunner.AndAsync("accede al submódulo \'Nueva Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
await testRunner.AndAsync("el usuario agrega el concepto \'400000437\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
await testRunner.AndAsync("ingresa la cantidad \'2\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
await testRunner.AndAsync("selecciona igv", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
await testRunner.AndAsync("selecciona al cliente con documento \'60587924\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
await testRunner.AndAsync("selecciona el tipo de comprobante \'BOLETA\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago en Efectivo - Condicion <condicion>")]
        [NUnit.Framework.CategoryAttribute("PagoEfectivo")]
        [NUnit.Framework.TestCaseAttribute("1", "CO", "100", null)]
        public async System.Threading.Tasks.Task PagoEnEfectivo_CondicionCondicion(string condicion, string tipo_Pago, string recibido, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PagoEfectivo"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("recibido", recibido);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago en Efectivo - Condicion <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 17
 await testRunner.WhenAsync(string.Format("el usuario selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.AndAsync("el usuario selecciona el medio de pago \'EF\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync(string.Format("el usuario ingresa el monto recibido \'{0}\'", recibido), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago con Tarjeta de Credito - Condicion <condicion>")]
        [NUnit.Framework.CategoryAttribute("TarjetaCredito")]
        [NUnit.Framework.TestCaseAttribute("3", "\"CO\"", "\"SCOTIABANK\"", "\"VISA\"", "\"1234567890\"", null)]
        public async System.Threading.Tasks.Task PagoConTarjetaDeCredito_CondicionCondicion(string condicion, string tipo_Pago, string nombre_Banco, string tipo_Tarjeta, string numero_Operacion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TarjetaCredito"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("nombre_banco", nombre_Banco);
            argumentsOfScenario.Add("tipo_tarjeta", tipo_Tarjeta);
            argumentsOfScenario.Add("numero_operacion", numero_Operacion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago con Tarjeta de Credito - Condicion <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.WhenAsync(string.Format("selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.AndAsync("selecciona el medio de pago \'TCRE\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync(string.Format("ingresa nombre del banco \'{0}\'", nombre_Banco), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync(string.Format("selecciona tipo de tarjeta \'{0}\'", tipo_Tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync(string.Format("ingresa número de operación \'{0}\'", numero_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago con Tarjeta de Débito - Condición <condicion>")]
        [NUnit.Framework.CategoryAttribute("TarjetaDebito")]
        [NUnit.Framework.TestCaseAttribute("8", "\"CO\"", "\"SCOTIABANK\"", "\"VISA\"", "\"1234567890\"", null)]
        public async System.Threading.Tasks.Task PagoConTarjetaDeDebito_CondicionCondicion(string condicion, string tipo_Pago, string nombre_Banco, string tipo_Tarjeta, string numero_Operacion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TarjetaDebito"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("nombre_banco", nombre_Banco);
            argumentsOfScenario.Add("tipo_tarjeta", tipo_Tarjeta);
            argumentsOfScenario.Add("numero_operacion", numero_Operacion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago con Tarjeta de Débito - Condición <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.WhenAsync(string.Format("selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
    await testRunner.AndAsync("selecciona el medio de pago \'TDEB\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync(string.Format("ingresa nombre del banco \'{0}\'", nombre_Banco), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync(string.Format("selecciona tipo de tarjeta \'{0}\'", tipo_Tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync(string.Format("ingresa número de operación \'{0}\'", numero_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago por Transferencia - Condición <condicion>")]
        [NUnit.Framework.CategoryAttribute("Transferencia")]
        [NUnit.Framework.TestCaseAttribute("19", "Contado", "\"001103180100023457\"", "\"TT00112233\"", null)]
        public async System.Threading.Tasks.Task PagoPorTransferencia_CondicionCondicion(string condicion, string tipo_Pago, string cuenta_Correcta, string numero_Operacion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Transferencia"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("cuenta_correcta", cuenta_Correcta);
            argumentsOfScenario.Add("numero_operacion", numero_Operacion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago por Transferencia - Condición <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.WhenAsync(string.Format("selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.AndAsync("selecciona el medio de pago \'TRANFON\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync(string.Format("ingresa cuenta bancaria correcta \'{0}\'", cuenta_Correcta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync(string.Format("ingresa número de operación \'{0}\'", numero_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago por Deposito - Condición <condicion>")]
        [NUnit.Framework.CategoryAttribute("Transferencia")]
        [NUnit.Framework.TestCaseAttribute("20", "Contado", "\"001103180100023457\"", "\"TT00112233\"", null)]
        public async System.Threading.Tasks.Task PagoPorDeposito_CondicionCondicion(string condicion, string tipo_Pago, string cuenta_Correcta, string numero_Operacion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Transferencia"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("cuenta_correcta", cuenta_Correcta);
            argumentsOfScenario.Add("numero_operacion", numero_Operacion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago por Deposito - Condición <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 67
    await testRunner.WhenAsync(string.Format("selecciona el tipo de pago \'{0}\'", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
    await testRunner.AndAsync("selecciona el medio de pago \'DEPCU\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.AndAsync(string.Format("ingresa cuenta bancaria correcta \'{0}\'", cuenta_Correcta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.AndAsync(string.Format("ingresa número de operación \'{0}\'", numero_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pago con Crédito Configurado - Condición <condicion>")]
        [NUnit.Framework.CategoryAttribute("CreditoConfigurado")]
        [NUnit.Framework.TestCaseAttribute("27", "10", "2", "3 de cada mes", null)]
        public async System.Threading.Tasks.Task PagoConCreditoConfigurado_CondicionCondicion(string condicion, string cuota_Inicial_Menor_Total, string cuotas_Menor_Total, string selecciona_Dia, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreditoConfigurado"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condicion", condicion);
            argumentsOfScenario.Add("cuota_inicial_menor_total", cuota_Inicial_Menor_Total);
            argumentsOfScenario.Add("cuotas_menor_total", cuotas_Menor_Total);
            argumentsOfScenario.Add("selecciona_dia", selecciona_Dia);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pago con Crédito Configurado - Condición <condicion>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.WhenAsync("selecciona el tipo de pago \'CC\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.AndAsync(string.Format("verifica cuota inicial \'{0}\'", cuota_Inicial_Menor_Total), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync(string.Format("verifica cuotas totales \'{0}\'", cuotas_Menor_Total), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync(string.Format("selecciona día del mes de pago \'{0}\'", selecciona_Dia), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("genera cuota", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.ThenAsync("la venta se guarda correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
